sudo: false
language: java
jdk: oraclejdk7
addons:
 apt:
  packages:
  - libgtest-dev
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - DISPLAY=:99.0
  - GTEST_DIR=${TRAVIS_BUILD_DIR}/gtest
  - secure: JlyegDL2Py0e0PWdFrOWIw915LN30HXlqJjsYh69LXaRj/10l4Kf9SZIKKzX33Vs8Ng9GCbHRhu/LUBnPGMB2HIVYGbdfz6FKfavWb0pD6kfMiLZ7jAFQQly9681Vkscv5RwMGtRzTJA1T5zUFzB5PsKacBCh/vc5CDhJzHpF/s=
before_script:
 - mkdir gtest 
 - cd gtest
 - cp -r /usr/src/gtest/. .
 - ls
 - cmake CMakeLists.txt
 - make
 - cd $TRAVIS_BUILD_DIR
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
script:
- cd releng/org.yakindu.sct.releng
- mvn clean verify
- cd ../org.yakindu.sct.repository/target/repository
- zip -r updatesite.zip *.*
#deploy:
# skip_cleanup: true
#  provider: releases
#  api_key: ${GITHUB_TOKEN}
