sudo: false
language: java
jdk: oraclejdk7
addons:
 apt:
  packages:
  - libgtest-dev
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - DISPLAY=:99.0
  - GTEST_DIR=${TRAVIS_BUILD_DIR}/gtest
  matrix:
  - TARGET=Mars.target
  - TARGET=Luna.target
before_script:
 - mkdir gtest 
 - cd gtest
 - cp -r /usr/src/gtest/. .
 - ls
 - cmake CMakeLists.txt
 - make
 - cd $TRAVIS_BUILD_DIR
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
script:
- cd releng/org.yakindu.sct.releng
- mvn clean verify -P$TARGET
- cd ../org.yakindu.sct.repository/target
- zip -r updatesite.zip repository
- cd $TRAVIS_BUILD_DIR
deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
   secure: BSEYtMYXInrXum0eOmisxDIUw5puH1WycKmXvnBJKn3GeekCWV2UCF4Elocmkil8MBzYQ3LlpiihncBalvVEzpgyVEo1Z0wnxiQtatZU0gMuw6piu+Owi5Om/kB6J4DvZShLt5qWYGVynBRhGsC4jFYpakCSHySy3icg1wI1sfI=
  file: releng/org.yakindu.sct.repository/target/updatesite.zip
  on:
    tags: Yakindu/statecharts
    condition: "$TRAVIS_TAG =~ ^release.*$"
