sudo: false

jdk: oraclejdk7

cache:
  directories:
  - $HOME/.m2
 
 env: DISPLAY=:99.0

language: java
before_install:
 - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
script: 
 - cd releng/org.yakindu.sct.releng
 - mvn clean verify
